# Generated by Django 3.2 on 2021-05-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='uses',
            field=models.IntegerField(default=1),
        ),
    ]
