# Generated by Django 4.1.4 on 2023-01-10 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menutype'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menuType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.menutype'),
            preserve_default=False,
        ),
    ]
