# Generated by Django 4.1.4 on 2023-01-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_rating_rating'),
        ('core', '0003_menu_menutype'),
    ]

    operations = [
    ]
