# Generated by Django 4.1.4 on 2023-01-31 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_menu_vegetarian'),
        ('core', '0004_merge_0002_alter_rating_rating_0003_menu_menutype'),
    ]

    operations = [
    ]
