# Generated by Django 4.1.4 on 2023-02-22 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_badge_image_alter_image_image_alter_menu_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(default=datetime.date(2023, 2, 22)),
        ),
        migrations.AlterField(
            model_name='menutype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
