# Generated by Django 4.1.4 on 2023-02-26 14:21

import datetime
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_badge_image_alter_image_image_alter_menu_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(default=datetime.date(2023, 2, 26)),
        ),
    ]
