# Generated by Django 4.1.4 on 2023-03-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_menu_date_alter_menutype_name'),
        ('core', '0011_profil_picture_alter_menu_date'),
    ]

    operations = [
    ]
